# Generated by Django 3.2.5 on 2021-07-23 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('user_name', models.CharField(max_length=10, verbose_name='ユーザー名')),
                ('user_password', models.CharField(max_length=10, verbose_name='パスワード')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ユーザー',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('user_name', models.CharField(max_length=10, verbose_name='ユーザー名')),
                ('user_profile', models.TextField(max_length=100, verbose_name='プロフィール')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='ユーザーID')),
                ('user_images', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
