# Generated by Django 3.2.5 on 2021-07-22 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('user_name', models.CharField(max_length=10, verbose_name='ユーザー名')),
                ('user_password', models.CharField(max_length=10, verbose_name='パスワード')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ユーザー',
            },
        ),
    ]
