# Generated by Django 3.2.5 on 2021-07-23 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='reated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
