# Generated by Django 3.2.5 on 2021-07-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_userimage_reated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='user_id',
            new_name='user_id2',
        ),
        migrations.RenameField(
            model_name='userimage',
            old_name='user_images',
            new_name='user_images2',
        ),
    ]
