# Generated by Django 3.2.5 on 2021-07-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20210723_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='user_id2',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='userimage',
            old_name='user_images2',
            new_name='user_images',
        ),
    ]
