# Generated by Django 3.2.5 on 2021-07-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_auto_20210723_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='created_date',
            new_name='created_date2',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='user_id',
            new_name='user_id2',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='user_name',
            new_name='user_name2',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='user_profile',
            new_name='user_profile2',
        ),
    ]
