# Generated by Django 3.2.5 on 2021-07-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_auto_20210723_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='created_date2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user_id2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='user_name2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='user_password2',
        ),
    ]
