# Generated by Django 3.2.5 on 2021-07-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_auto_20210723_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_date2',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id2',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name2',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password2',
            new_name='user_password',
        ),
    ]
