# Generated by Django 3.2.5 on 2021-07-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_auto_20210723_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='user_images',
            field=models.ImageField(upload_to='image/', verbose_name='avator'),
        ),
    ]
