# Generated by Django 3.2.5 on 2021-07-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_auto_20210724_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
