# Generated by Django 3.2.5 on 2021-07-24 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0011_remove_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='delete_date',
            field=models.DateTimeField(null=True, verbose_name='削除日時'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='delete_flg',
            field=models.BooleanField(null=True, verbose_name='削除フラグ'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='group_flg',
            field=models.BooleanField(null=True, verbose_name='団体フラグ'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='sports_kind_cd',
            field=models.CharField(max_length=2, null=True, verbose_name='スポーツ種別コード'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_age',
            field=models.CharField(max_length=2, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_sex_cd',
            field=models.CharField(max_length=2, null=True, verbose_name='性別種別コード'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='user',
            name='delete_date',
            field=models.DateTimeField(null=True, verbose_name='削除日時'),
        ),
        migrations.AlterField(
            model_name='user',
            name='delete_flg',
            field=models.BooleanField(null=True, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_name',
            field=models.CharField(max_length=10, null=True, verbose_name='ユーザー名'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_profile',
            field=models.TextField(max_length=200, null=True, verbose_name='プロフィール'),
        ),
    ]
