# Generated by Django 3.2.5 on 2021-07-24 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0013_auto_20210724_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='ユーザーID')),
                ('like_user_id', models.CharField(max_length=10, verbose_name='いいねユーザーID')),
                ('from_to_cd', models.CharField(max_length=2, null=True, verbose_name='fromto種別コード')),
                ('delete_flg', models.BooleanField(null=True, verbose_name='削除フラグ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('delete_date', models.DateTimeField(null=True, verbose_name='削除日時')),
            ],
        ),
    ]
