# Generated by Django 3.2.5 on 2021-07-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0014_userlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlike',
            old_name='like_user_id',
            new_name='from_like_user_id',
        ),
        migrations.RenameField(
            model_name='userlike',
            old_name='user_id',
            new_name='to_like_user_id',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='from_to_cd',
        ),
    ]
