# Generated by Django 3.2.5 on 2021-07-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0016_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.user'),
        ),
    ]
