# Generated by Django 3.2.5 on 2021-07-24 12:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0018_auto_20210724_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='from_like_user_id',
        ),
        migrations.AddField(
            model_name='userlike',
            name='user_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='matching.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlike',
            name='to_like_user_id',
            field=models.CharField(max_length=10, verbose_name='いいねしたユーザーID'),
        ),
    ]
