# Generated by Django 3.2.5 on 2021-07-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0020_userlike_matching_flg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='matching_flg',
        ),
    ]
